---
- name: Create Repo location in /var/www/html
  ansible.builtin.file:
    path: /var/www/html/repo_files
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Configure BaseOS repo file
  ansible.builtin.template:
    src: rhel9_baseos.repo.j2
    dest: /var/www/html/repo_files/rhel9_baseos.repo

- name: Configure AppStream repo file
  ansible.builtin.template:
    src: rhel9_appstream.repo.j2
    dest: /var/www/html/repo_files/rhel9_appstream.repo

- name: Configure CodeReady Builder repo file
  ansible.builtin.template:
    src: rhel9_crb.repo.j2
    dest: /var/www/html/repo_files/rhel9_crb.repo

- name: Configure EPEL repo file
  ansible.builtin.template:
    src: epel9.repo.j2
    dest: /var/www/html/repo_files/epel9.repo

- name: Configure Docker CE repo file
  ansible.builtin.template:
    src: docker-ce.repo.j2
    dest: /var/www/html/repo_files/docker-ce.repo
