---
- name: Enable CodeReady Builder repository using RHSM
  community.general.rhsm_repository:
    name: codeready-builder-for-rhel-9-x86_64-rpms
    state: enabled

- name: Get Docker CE Repo File checksum
  ansible.builtin.shell:
    cmd: |
      curl -sSL https://download.docker.com/linux/rhel/docker-ce.repo | openssl dgst -sha256 | cut -d " " -f 2
  register: docker_repo_checksum_result

- name: Set fact for Docker CE Repo File checksum
  ansible.builtin.set_fact:
    docker_repo_checksum: '{{ docker_repo_checksum_result.stdout }}'

- name: Enable Docker Community Edition Repo
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/rhel/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo
    mode: '0444'
    checksum: sha256:{{ docker_repo_checksum }}

- name: Import EPEL GPG key
  ansible.builtin.rpm_key:
    key: https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-9
    state: present

- name: Install required packages
  ansible.builtin.dnf:
    name:
      - httpd
      - rsync
      - yum-utils
      - policycoreutils-python-utils
      - https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm
    update_cache: true
    state: present
