---
- name: Disable Apache welcome page
  ansible.builtin.replace:
    path: /etc/httpd/conf.d/welcome.conf
    regexp: '^(?!#)(.*)$'
    replace: '# \1'
  notify: Restart httpd

- name: Deploy httpd configuration
  ansible.builtin.template:
    src: httpd.conf.j2
    dest: /etc/httpd/conf.d/localrepo.conf
  notify: Restart httpd

- name: Open firewall for HTTP
  ansible.posix.firewalld:
    port: "80/tcp"
    permanent: true
    immediate: true
    state: enabled

- name: Configure httpd SELinux
  when: ansible_selinux.status == 'enabled'

  block:
    - name: Set SELinux context for repository directory
      community.general.sefcontext:
        target: "/var/www/html(/.*)?"
        setype: httpd_sys_content_t

    - name: Restore SELinux context
      ansible.builtin.command: restorecon -Rv /var/www/html
