---
- name: Sync {{ repo_sync.name }} repository
  ansible.builtin.command: reposync -p "{{ repo_sync.path }}" --downloadcomps --download-metadata --repoid="{{ repo_sync.repoid }}"
  register: reposync_result
  failed_when: reposync_result.rc != 0
  retries: 3
  delay: 5
  loop: "{{ repositories }}"
  loop_control:
    loop_var: repo_sync

- name: Ensure GPG key directory exists
  ansible.builtin.file:
    path: /var/www/html/rhel/9/keys
    state: directory
    mode: '0755'

- name: Download GPG keys
  ansible.builtin.get_url:
    url: "{{ key.url }}"
    dest: /var/www/html/rhel/9/keys/{{ key.dest }}"
    mode: '0644'
  loop: "{{ gpg_keys }}"
  loop_control:
    loop_var: key
