---
name: Linting
on:
  push:
    branches: [ main ] # Or your main branch name
  pull_request:
    branches: [ main ] # Or your main branch name
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required for some linters to work properly
      - name: Set up Python 3.x
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ansible-lint yamllint
      - name: Ansible Lint
        run: ansible-lint .
      - name: Yaml Lint
        run: yamllint .
